# Generated by Django 5.1.7 on 2025-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_set_valid_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='popup_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
